config:
    warningsAsErrors: false

complexity:
    active: true
    TooManyFunctions:
        thresholdInFiles: 30
        thresholdInClasses: 20
        ignorePrivate: true

style:
    active: false

naming:
    TopLevelPropertyNaming:
        constantPattern: '[A-Z][A-Za-z0-9]*'
    FunctionNaming:
        ignoreAnnotated: [ 'Composable', 'Preview' ]

output-reports:
    exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'MdOutputReport'
